name: Postman

on:
  
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Check version Newman and Node
        run: |
          newman --version
          node --version

     
      - name: Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Execute collection
        run: newman run ./desafioTecnico.postman_collection.json -e ./Repositorio.postman_environment.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
        
